POST https://rocky-spire-54542.herokuapp.com/couponCode/validate
Content-Type: application/json

{
    "coupon":"MJAMBGZ10",
    "amount":999
}

###

POST https://rocky-spire-54542.herokuapp.com/couponCode
Content-Type: application/json

{
    "coupon": "MJAMBGZ10",
    "type": "FLAT",
    "expDate":"2020-07-10",
    "minAmount": 700,
    "amountOff": 50
}

###
